### ISSUE TITLE
`add_sheets_prefix` function

### ISSUE THREAD

**Issue by danielebottigliengo** [UBESP-DCTV/tipnet.ubesp#7]
Probabilmente andrebbero definiti i pacchetti delle funzioni `str_detect` e `ui_stop` (riga 42 e riga 43):

- `stringr::str_detect`
- `usethis::ui_stop`

**Comment by CorradoLanera** [comment]
Nella documentazione della funzione avevo aggiunto l'istruzione
```
#' @ImportFrom stringr str_detect
```
Che permette quindi di avere la funzione disponibile senza doverne richiamare esplicitamente il pacchetto. Sono d'accordo che in questo caso è meglio essere espliciti (non ricordo perchè lo avessi fatto... quindi vuol dire che non ha più senso di essere così!)

Riguardo invece ai comandi di interfaccia di {usethis} li ho importati dierttamente tutti (è proprio il lavoro di `depigner::use_ui()`, se guardi nel namespace infatti compare tutto quanto importato dal pacchetti, sia come pacchetti che come funzioni specifiche). Questo l'ho fatto eprchè tali funzioni le uso con altissima frequenza e anche annidate una dentro l'altra..se devo ogni volta scrivere `usethis::` faccio righe di testo lunghe due km per non scrivere nulla, e quindi ho rpeferito così :-) (Se vuoi andare a vedere avevo aperto un issue discusso con JB a tal proposito ma hanno preferito non incorporare una funzione che lo facesse in modo esplicito (come per esempio avviene con `usethis::use_pipe()`) e quindi l'ho messa nel {depigner} :-))
