### ISSUE TITLE
Add run-time test to `db_update_from_server`

### ISSUE THREAD

**Issue by danielebottigliengo** [UBESP-DCTV/tipnet.ubesp#9]
Aggiungerei alla funzione `db_update_from_server` un test interno per controllare che il file name sia un rds. Una cosa del tipo:

`if(stringr::str_detect(file_name, ".rds$", negate = TRUE)) {
        usethis::ui_stop("The data must be stored in a '.rds' file.")
    }`

**Comment by CorradoLanera** [comment]
Ho eliminato la possibilità di dare un nome esplicito. In caso ne riparleremo più avanti se sarà necessario. Per ora, credo non serva poter scegliere il nome.
